spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chongdetang?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: cdt
    password: 123456
