create table culture
(
    id          int auto_increment
        primary key,
    date        date         null comment '文章发布日期',
    title       varchar(100) null comment '文章标题',
    url         varchar(100) null comment '文章网址',
    type        varchar(100) null comment '子板块类型',
    description varchar(500) null comment '文章摘要',
    photo       varchar(100) null comment '文章标题配图标识符'
)
    comment '文化知识内容表';

INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (2, '2021-06-11', '梁巘·承晋斋积闻录', 'https://www.cdtde.com/whzs/shuhazhuanke/288.html', 'shzk', '执笔论 书大字，笔锋须瘦硬。盖笔锋瘦硬，落纸时极力揉挫，沈着而不肥浊，否则肥浊矣。观东坡《罗池庙》，山谷《戏米元章帖》，皆瘦硬笔锋所书，故或挫或提，肥瘦如意，必非秃...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (3, '2021-06-11', '何绍基·论书', 'https://www.cdtde.com/whzs/shuhazhuanke/287.html', 'shzk', '跋陈叙斋藏赵文敏书千文 智师真草《千字文》，草书分行比格，与真书齐同，故意近章草，而少参差超迈之趣。惟怀素小草书《千文》，神明变化，妙极古穆。文敏为此，使转纵横有自...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (4, '2021-06-11', '傅山·作字示儿孙', 'https://www.cdtde.com/whzs/shuhazhuanke/286.html', 'shzk', '作字先作人，人奇字自古。纲常叛周孔，笔墨不可补。诚悬有至论，笔力不专主。一臂加五指，乾卦六爻睹。谁为用九者，心与孥是取。永兴逆羲文，不易柳公语。未习鲁公书，先观鲁...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (5, '2021-06-11', '傅山·散论', 'https://www.cdtde.com/whzs/shuhazhuanke/285.html', 'shzk', '作小楷，须用大力，柱笔著纸，如以千金（斤）铁杖柱地。若谓小字无须重力，可以飘忽点缀而就，便于此技说梦。写黄庭经数千过，了用圆锋，笔香象力，竭诚运腕，肩背供筋骨之输...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (6, '2021-06-11', '晋·卫铄·笔阵图', 'https://www.cdtde.com/whzs/shuhazhuanke/284.html', 'shzk', '夫三端之妙，莫先乎用笔；六艺之奥，莫重乎银钩。昔秦丞相斯所见周穆王书，七日兴叹，患其无骨。蔡尚书邕入鸿都观碣，十旬不返，嗟其出群。故知达其源者少，暗于理者多。近代...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (7, '2021-06-11', '汉·蔡邕·篆势、笔论、九势', 'https://www.cdtde.com/whzs/shuhazhuanke/283.html', 'shzk', '篆势 字画之始，因于鸟迹，仓颉循圣，作则制文。体有六篆，要妙入神。或象龟文，或比龙鳞，纡体效尾，长翅短身。颓若黍稷之垂颖，蕴若虫蛇之棼緼。扬波振激，鹰跱觯鸟震，延颈...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (8, '2021-06-11', '蔡邕《 九势 》（四）', 'https://www.cdtde.com/whzs/shuhazhuanke/282.html', 'shzk', '原文：夫书肇于自然，自然既立，阴阳生焉；阴阳既生，形势出矣。藏头护尾，力在字中，下笔用力，肌肤之丽。故曰：势来不可止，势去不可遏，惟笔软则奇怪生焉。 凡落笔结字，上...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (9, '2021-06-11', '蔡邕《 九势 》（三）', 'https://www.cdtde.com/whzs/shuhazhuanke/281.html', 'shzk', '明董其昌题宋拓《智永真草千字文》 原文：夫书肇于自然，自然既立，阴阳生焉；阴阳既生，形势出矣。藏头护尾，力在字中，下笔用力，肌肤之丽。故曰：势来不可止，势去不可遏，...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (10, '2021-06-11', '蔡邕《 九势 》（二）', 'https://www.cdtde.com/whzs/shuhazhuanke/280.html', 'shzk', '王铎草书诗卷局部 原文：夫书肇于自然，自然既立，阴阳生焉；阴阳既生，形势出矣。藏头护尾，力在字中，下笔用力，肌肤之丽。故曰：势来不可止，势去不可遏，惟笔软则奇怪生焉...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (11, '2021-06-11', '蔡邕《九势》（一）', 'https://www.cdtde.com/whzs/shuhazhuanke/279.html', 'shzk', '蔡邕（133～192年），东汉文学家、书法家。字伯喈，陈留圉（今河南杞县南）人。灵帝时为议郎等官。献帝时，拜左中郎将。迁都长安后，封高阳乡侯。董卓遭诛后，他亦被捕，死于狱...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (12, '2021-05-19', '书法草圣：张芝', 'https://www.cdtde.com/whzs/shuhazhuanke/215.html', 'shzk', '张芝，字伯英，東漢末年著名书法家，被称为草圣。 他的草书精劲绝伦，将当时章草创新为今草。据说他王 临池学书，池水尽黑。 羲之推崇钟繇、张芝两家，狂草大师怀素承认从二张...', 'http://cdtde.com/uploads/allimg/210519/163A95157-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (13, '2021-05-19', '历代书法之隶书', 'https://www.cdtde.com/whzs/shuhazhuanke/214.html', 'shzk', '隶书的发明： 隶书起源于秦朝，相传程邈得罪秦始皇，在监狱里发明了隶书；当然也因此得到了豁免。在東漢时期达到顶峰，书法界有漢隶唐楷之称。现在仍有很多東漢时期的碑文。最...', 'http://cdtde.com/uploads/allimg/210519/1635462093-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (14, '2021-05-19', '最早的书法家：李斯', 'https://www.cdtde.com/whzs/shuhazhuanke/213.html', 'shzk', '大篆是个笼统的称谓，指秦朝以前的文字；小篆专指秦朝文字。秦始皇帝横扫六合，征服了当时華夏文明区，统一律度量衡。当然，还有书同文，车同轨；文字的统一，这就是小篆。...', 'http://cdtde.com/uploads/allimg/210519/16343322U-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (15, '2021-05-19', '最早的书法：甲骨文、金文、石鼓文', 'https://www.cdtde.com/whzs/shuhazhuanke/212.html', 'shzk', '书画同源，画传其形，书传其意。甲骨文佐证了这个论断。有意思的是，毕加索画过一系列牛的示范图，第一个是完全的写实，力求再现真实的牛的样子，最后一个就只是个轮廓了。其...', 'http://cdtde.com/uploads/allimg/210519/1632251553-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (16, '2021-05-19', '中華艺术的巅峰：书圣「王羲之」', 'https://www.cdtde.com/whzs/shuhazhuanke/211.html', 'shzk', '关于王羲之： 王羲之（303年－361年），東晋时书法家，字逸少，官拜右军将军，人称王右军。原籍琅邪临沂（今属山东），随西晋的崩溃後迁居山阴（今浙江绍兴）。王羲之在书法上的...', 'http://cdtde.com/uploads/allimg/210519/1629561O8-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (17, '2021-05-19', '六朝画圣：张僧繇', 'https://www.cdtde.com/whzs/shuhazhuanke/210.html', 'shzk', '南朝梁时画家张僧繇，是顾恺之、陆探微齐名的大画家。 相传他在金陵安乐寺画了四条龙，给其中的二条龙点上了眼睛，这两条龙便腾云驾雾地飞到天上去了，而未点睛者仍在墙壁上。...', 'http://cdtde.com/uploads/allimg/210519/162J050I-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (18, '2021-05-19', '南朝画圣陆探微', 'https://www.cdtde.com/whzs/shuhazhuanke/209.html', 'shzk', '陆探微 陆探微（？ - 约 485 ）是南朝苏州地区画家。 南朝艺术理论家谢赫在其《古画品录》中将他评为第一品第一人，说他的绘画：穷理尽性，包前孕后，古今独立。 陆探微运用草...', 'http://cdtde.com/uploads/allimg/210519/1625421951-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (19, '2021-05-18', '德印赏析——归一德，汇天下心', 'https://www.cdtde.com/whzs/shuhazhuanke/204.html', 'shzk', '《自强不息 厚德载物》 自强不息，厚德载物，出自《周易》中的卦辞：天行健，君子以自强不息；地势坤，君子以厚德载物。两句意谓：天(即自然)的运动刚强劲健，相应于此，君子处...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (20, '2021-05-18', '印与信，艺术与智慧来源于生活必将回归于生活', 'https://www.cdtde.com/whzs/shuhazhuanke/203.html', 'shzk', '中国印（篆刻）,连同书法、绘画、诗歌并称中国四大传统艺术。 明周公瑾《印说》云：印者何？信也，印从爪何？手持信也，从节何？节表信也。以字释意，印字的左半部是个爪字，...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (21, '2021-05-18', '方方正正中国印，堂堂正正中国人，以印为行', 'https://www.cdtde.com/whzs/shuhazhuanke/202.html', 'shzk', '中华民族有五千多年的文明历史，创造了灿烂的中华文明，为人类作出了卓越贡献，成为世界上伟大的民族。而这，首当其冲的应该是这数千年一脉相承的文字文明。 而篆刻、印章更是...', 'http://cdtde.com/uploads/allimg/210518/2206115M6-5-lp.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (22, '2022-11-16', '知识分享：何为寿德匾', 'https://www.cdtde.com/whzs/bianeyinglian/402.html', 'beyl', '在中国古代专门为德高望重的老人祝寿时赠送的匾额称为寿德匾。 崇德堂博物馆收藏德寿齐 辉 匾 为老人祝寿，也是我们中华民族优秀传统文化的一个重要组成部分。一块牌匾体现的是...', 'http://cdtde.com/uploads/allimg/221116/1-221116105I4449-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (23, '2022-08-08', '知识分享 | 传承匾额文化', 'https://www.cdtde.com/whzs/bianeyinglian/389.html', 'beyl', '匾额的章法 一块好的匾额，就是一本立体书，就是一段历史典故，就是一个传奇人生，就是一个荣耀的象征，就是一个家族世世代代引以自豪的金字招牌。 所以，一块完整的匾额要由...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (24, '2021-06-11', '浅谈中国楹联起源', 'https://www.cdtde.com/whzs/bianeyinglian/292.html', 'beyl', '一、哲学探源：物生有两、事不孤立 楹联者，对仗之文学也。这种语言文字的平行对称，与哲学中所谓太极生两仪，即把世界万事万物分为相互对称的阴阳两半，在思维本质上极为相通...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (25, '2021-06-11', '楹联中的情趣', 'https://www.cdtde.com/whzs/bianeyinglian/291.html', 'beyl', '在祖国的传统文化中，除了诗词歌赋外，被誉为诗中之诗的楹联，也有它独特的魅力。它作为语言艺术和书法艺术的结合体，不仅在我国灿烂的文化艺术殿堂中占有席位，而且最为广大...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (26, '2021-06-11', '如何选择春联?', 'https://www.cdtde.com/whzs/bianeyinglian/290.html', 'beyl', '春联既是根据我国古代骈体文衍生出来的一种新文体，又是借鉴了我国诗歌传统的文学形式。它与古代的骈体文和诗歌不同，是一种特有形式的独立文体。尽管律诗或骈文中的对仗句，...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (27, '2021-06-11', '春联艺术的特点', 'https://www.cdtde.com/whzs/bianeyinglian/289.html', 'beyl', '复字联：同一个字非连续重复出现。 顶针联：前一个分句的句脚字，作为后一个分句的句头字。 嵌字联：包括嵌入序数、方位、节气、年号、姓氏、人名、地名、物名（如药名）等。...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (28, '2021-05-18', '故宫大殿上牌匾背后的故事你可知道？', 'https://www.cdtde.com/whzs/bianeyinglian/210.html', 'beyl', '在前面紫禁城里些牌匾背后的国家哲学（一）这边文章里，分别为大家分享了故宫太和殿建极绥猷匾、中和殿允执厥中匾、保和殿皇建有极匾背后的故事，今天接着分享故宫另外几块耳...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (29, '2021-05-18', '紫禁城那些牌匾背后的国家哲学，你知道多少？', 'https://www.cdtde.com/whzs/bianeyinglian/200.html', 'beyl', '故宫旧称紫禁城，是中国明清两代的皇家宫殿，是世界上最大的皇家建筑，也是至今世界上保存最完整的古代宫殿建筑群，在故宫的每个大殿上，都会有皇帝亲笔题写的匾额，如大家经...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (30, '2021-05-18', '浅谈匾额文化之匾额性质分类', 'https://www.cdtde.com/whzs/bianeyinglian/199.html', 'beyl', '前面有和大家分享匾额在中国文化的影响与发展，今天和大家在根据匾额的功能与性质的分类。 匾额按其性质来说，比较常见的大致可以分为七类 第一类是堂号匾 一般文人墨客，都会...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (31, '2021-05-18', '浅谈中国传统匾额文化（匾额文化起源与发展）', 'https://www.cdtde.com/whzs/bianeyinglian/198.html', 'beyl', '中国的匾额自发明之始，就离不开刻字艺术，而中国的刻字艺术历史久远《易系辞》上说：上古结绳而治，后世圣人易之以书契。这里的书契就是锲刻文字。追溯渊源，中国新石器时代...', 'http://cdtde.com/uploads/allimg/210518/1-21051R1543B09-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (32, '2021-06-11', '拓片制作流程揭秘', 'https://www.cdtde.com/whzs/tuopiandiaoban/304.html', 'tpdk', '工具： 1，塑料工具箱一个，装工具（到处都有卖的，你们不必自己再去学塑料成型加工工艺了） 2，塑料喷壶一只，用来发纸（就是理发店喷水的，或者你们家喷花的） 3，棕刷一只，...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (33, '2021-06-11', '山东青岛一收藏家收藏千余块汉画像砖 无处存放', 'https://www.cdtde.com/whzs/tuopiandiaoban/303.html', 'tpdk', '现在青岛有一名收藏了1100多块珍贵汉画像砖的收藏家张新宽，作为个人收藏家，他遇到了收藏品无处放置的难题，希望政府有关部门能出台政策，鼓励民间收藏的发展。在本次两会上，...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (34, '2021-06-11', '画像石拓片题跋的内容（仅供参考）', 'https://www.cdtde.com/whzs/tuopiandiaoban/302.html', 'tpdk', '(一) 伏羲女娲捧月 此画像石出土在江苏徐州附近农村的东汉时期的墓室中,规格为40*40厘米，属汉带代画像石中的精品 伏羲女娲以对偶神的构图形式出现，女娲,伏羲手中捧着着日，两神...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (35, '2021-06-11', '汉代墓葬中的车马出行图研究', 'https://www.cdtde.com/whzs/tuopiandiaoban/301.html', 'tpdk', '在以墓室壁画、画像石和画像砖为代表的汉代画像中，车马出行图是最常见的画像题材。车马出行图，不仅数量大，而且刻画生动，气魄恢弘，是汉代画像中最典型、最精彩的部分之一...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (36, '2021-06-11', '汉画中的车马出行图', 'https://www.cdtde.com/whzs/tuopiandiaoban/300.html', 'tpdk', '车马出行图刻画生动，气魄恢弘，是汉代画像中最典型、最精彩的部分之一 《后汉书舆服志》中记载的汉代车的等级制度，是我们能见到的较早对车分级的规定。自天子以下至太皇、太...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (37, '2021-06-11', '拓片的人文价值', 'https://www.cdtde.com/whzs/tuopiandiaoban/299.html', 'tpdk', '金书拓片是具有鲜明东方艺术特色的文化遗物和内涵丰富的收藏品。拓片是用中国人的传綂手法去表现中国古代器物，是中国特殊的文化载体，在它身上凝结了一种难以名状的金石气息...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (38, '2021-06-11', '什么叫拓片', 'https://www.cdtde.com/whzs/tuopiandiaoban/298.html', 'tpdk', '用墨把石刻和古器物上的文字及花纹拓在纸上后的成品。这种拓印行为也称为拓片。拓片是从原物直接拓印下来的，大小和形状与原物相同，是一种科学记录的方法。除有凹凸纹饰的器...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (39, '2021-06-11', '汉画难道不值得我们去研究吗?', 'https://www.cdtde.com/whzs/tuopiandiaoban/297.html', 'tpdk', '汉朝是我国历史上最为强盛的朝代之一,也是当时世界上在工业,农业,商业上高度发达,政治,军事.文化,艺术等领域领先世界各国的强大帝国，是一个让国人为之骄傲的时代。历代封建王朝...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (40, '2021-06-11', '碑帖拓片的鉴别方法', 'https://www.cdtde.com/whzs/tuopiandiaoban/296.html', 'tpdk', '碑帖拓片包括刻帖和碑拓片。碑的原意是指无文字的竖石，后来，凡刻有文字的石头皆可称碑，这大约是汉以后的事。而今，除刻帖之外，一切刻有文字的石刻，包括碣、墓志、塔铭、...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (41, '2021-06-11', '碑帖拓片的制作方法', 'https://www.cdtde.com/whzs/tuopiandiaoban/295.html', 'tpdk', '一直对制作碑刻拓片很感兴趣，听朋友介绍，碑刻拓片的制作要在春，秋天为宜。因为其他缘故也有在其他季节制作的，但是很少。有兴遇到了制作拓片的场景，在我的要求下，工作人...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (42, '2021-06-11', '另一种拓片的制作方法', 'https://www.cdtde.com/whzs/tuopiandiaoban/294.html', 'tpdk', '怎样制作拓片？ 我国名碑帖刻石，为了避免自然灾害对它们的损坏，自宋以来，采取了集中保护的方法。在宋代元右二年（1087年），为了保存开成石经，建立了西安碑林，九百多年来...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (43, '2021-06-11', '汉画像石拓片收藏', 'https://www.cdtde.com/whzs/tuopiandiaoban/293.html', 'tpdk', '汉画像石艺术以深沉博大、粗犷古朴的独特风格显现出它特有的艺术魅力，引起人们的兴趣，以致竞相传拓，饮誉海内外。 汉画是指汉代遗留下来的画像石、画像砖、墓室壁画，以及帛...', 'http://cdtde.com/images/defaultpic.gif');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (44, '2021-05-19', '字活话你知 --“中国四大印刷字体”', 'https://www.cdtde.com/whzs/zaozhiyinshua/208.html', 'zzys', '宋体 （中国大陆一般称宋体； 台湾、香港地区一般称明体） 起源 宋体字是在刻书字体的基础上发展起来的，源于唐代，随着宋代（两宋）雕版印刷的繁荣而获得极大的发展，到明代逐...', 'http://cdtde.com/uploads/allimg/210519/1623263309-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (45, '2021-05-19', '小知识│何谓活字印刷术？', 'https://www.cdtde.com/whzs/zaozhiyinshua/207.html', 'zzys', '1 何 谓活字刷术？ 活字印刷术，也称为活版印刷术，也称为活字排版印刷术、摆版印刷术。这种技术大约有四道工序：一是制字；二是拣字排版；三是敷墨铺纸刷印；四是有序贮字。其...', 'http://cdtde.com/uploads/allimg/210519/161ZH103-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (46, '2021-05-19', '书本的3000年进化史', 'https://www.cdtde.com/whzs/zaozhiyinshua/206.html', 'zzys', '中国最早出现的系统性文字，当属闻名世界的殷墟甲骨文，起初是用来做占卜，由于字是刻在龟甲兽骨上，故而得名。 但是甲骨文有个问题，那就是，龟甲兽骨之类形状不规则，用来刻...', 'http://cdtde.com/uploads/allimg/210519/161I06217-0-lp.jpg');
INSERT INTO chongdetang.culture (id, date, title, url, type, description, photo) VALUES (47, '2021-05-19', '十周年倒带，看“和”字活了', 'https://www.cdtde.com/whzs/zaozhiyinshua/205.html', 'zzys', '转眼十年过去了， 2008年北京 奥运会那会儿虾米才上初二，当时开幕式看也就看过了，震撼过后没太多感觉，现在重新看倒是发现不少亮点，结合解说风味更佳。 解说： 中国汉字是世...', 'http://cdtde.com/uploads/allimg/210519/1614002930-0-lp.jpg');
